"""drop account_holdings; restrict transaction_entries.account_id

Revision ID: 13d3894d80e5
Revises: 9ee7d5fc9bbd
Create Date: 2026-05-10 18:37:55.677369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13d3894d80e5"
down_revision: Union[str, Sequence[str], None] = "9ee7d5fc9bbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account_holdings")
    op.drop_constraint(op.f("fk_transaction_entries_account_id_accounts"), "transaction_entries", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_transaction_entries_account_id_accounts"), "transaction_entries", "accounts", ["account_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_transaction_entries_account_id_accounts"), "transaction_entries", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_transaction_entries_account_id_accounts"), "transaction_entries", "accounts", ["account_id"], ["id"], ondelete="CASCADE"
    )
    op.create_table(
        "account_holdings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("asset_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=28, scale=18), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], name=op.f("fk_account_holdings_account_id_accounts"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], name=op.f("fk_account_holdings_asset_id_assets"), ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_holdings")),
        sa.UniqueConstraint(
            "account_id",
            "asset_id",
            name=op.f("uq_account_holdings_account_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
