"""create assets table

Revision ID: 30935be92867
Revises: 9c21dfe94dce
Create Date: 2026-05-07 23:19:17.739723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30935be92867"
down_revision: Union[str, Sequence[str], None] = "9c21dfe94dce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum("fiat", "stock", "crypto", "future", name="asset_type_enum", native_enum=False, create_constraint=True, length=16),
            nullable=False,
        ),
        sa.Column("asset_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("asset_name", name=op.f("uq_assets_asset_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assets")
    # ### end Alembic commands ###
