"""partial unique index on active accounts

Revision ID: 5c4775302ab4
Revises: 13d3894d80e5
Create Date: 2026-05-16 18:41:34.258377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c4775302ab4"
down_revision: Union[str, Sequence[str], None] = "13d3894d80e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_accounts_user_id"), "accounts", type_="unique")
    op.create_index(
        "uq_account_user_name_active", "accounts", ["user_id", "name"], unique=True, postgresql_where=sa.text("NOT is_archived")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_account_user_name_active", table_name="accounts", postgresql_where=sa.text("NOT is_archived"))
    op.create_unique_constraint(op.f("uq_accounts_user_id"), "accounts", ["user_id", "name"], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
