"""add trades table and trade_id on transactions

Revision ID: 6de227cafe25
Revises: 5c4775302ab4
Create Date: 2026-05-17 14:43:14.418488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6de227cafe25"
down_revision: Union[str, Sequence[str], None] = "5c4775302ab4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "side",
            sa.Enum("buy", "sell", name="trade_side_enum", native_enum=False, create_constraint=True, length=16),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=28, scale=18), nullable=False),
        sa.Column("price_per_unit", sa.Numeric(precision=28, scale=18), nullable=False),
        sa.Column("fees", sa.Numeric(precision=28, scale=18), server_default="0", nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_trades_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_trades_asset_id_assets"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_trades_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
    )
    op.add_column("transactions", sa.Column("trade_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_transactions_trade_id_trades"), "transactions", "trades", ["trade_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_transactions_trade_id_trades"), "transactions", type_="foreignkey")
    op.drop_column("transactions", "trade_id")
    op.drop_table("trades")
    # ### end Alembic commands ###
