"""Small modifications to table ondelete

Revision ID: 83808db4ce6c
Revises: 52ebf80aa2fa
Create Date: 2026-05-09 22:41:03.069744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83808db4ce6c'
down_revision: Union[str, Sequence[str], None] = '52ebf80aa2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transaction_entries_account_id_accounts'), 'transaction_entries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transaction_entries_account_id_accounts'), 'transaction_entries', 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transaction_entries_account_id_accounts'), 'transaction_entries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transaction_entries_account_id_accounts'), 'transaction_entries', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
