"""Created account holdings

Revision ID: 86ad5648d77f
Revises: 086a3a36e54c
Create Date: 2026-05-09 13:41:12.063165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ad5648d77f'
down_revision: Union[str, Sequence[str], None] = '086a3a36e54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_account_holdings_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_account_holdings_asset_id_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_holdings')),
    sa.UniqueConstraint('account_id', 'asset_id', name=op.f('uq_account_holdings_account_id'))
    )
    op.drop_constraint(op.f('uq_accounts_user_id_name'), 'accounts', type_='unique')
    op.create_unique_constraint(op.f('uq_accounts_user_id'), 'accounts', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_accounts_user_id'), 'accounts', type_='unique')
    op.create_unique_constraint(op.f('uq_accounts_user_id_name'), 'accounts', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_table('account_holdings')
    # ### end Alembic commands ###
