"""Added is archived field

Revision ID: 9ee7d5fc9bbd
Revises: 83808db4ce6c
Create Date: 2026-05-09 23:19:22.997518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee7d5fc9bbd'
down_revision: Union[str, Sequence[str], None] = '83808db4ce6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('fk_transaction_entries_account_id_accounts'), 'transaction_entries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transaction_entries_account_id_accounts'), 'transaction_entries', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transaction_entries_account_id_accounts'), 'transaction_entries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transaction_entries_account_id_accounts'), 'transaction_entries', 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('accounts', 'is_archived')
    # ### end Alembic commands ###
