"""Modified asset table

Revision ID: f73140ca125a
Revises: 30935be92867
Create Date: 2026-05-09 11:30:08.150321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73140ca125a'
down_revision: Union[str, Sequence[str], None] = '30935be92867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('symbol', sa.String(length=20), nullable=False))
    op.add_column('assets', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('uq_assets_asset_name'), 'assets', type_='unique')
    op.create_unique_constraint(op.f('uq_assets_symbol'), 'assets', ['symbol'])
    op.drop_column('assets', 'asset_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_assets_symbol'), 'assets', type_='unique')
    op.create_unique_constraint(op.f('uq_assets_asset_name'), 'assets', ['asset_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'name')
    op.drop_column('assets', 'symbol')
    # ### end Alembic commands ###
